### ISSUE TITLE
apng's with transparent alpha, appear blown out

### ISSUE THREAD

**Issue by tettoffensive** [onevcat/APNGKit#10]
Loading in an apng appears to just assign alpha values of 1 or 0. Any alpha values above 0 appear to be clamped to 1. When I look at the apng's in Finder/Preview on a mac, the alpha works fine.

**Comment by pcperini** [comment]
:+1:

**Comment by onevcat** [comment]
Should be fixed in version 0.3.1 (as well as in swift2.3 branch).
