### ISSUE TITLE
Tag version 1.2.1 has not been released to CocoaPods, yet.

### ISSUE THREAD

**Issue by imbrig** [onevcat/APNGKit#104]
I don't know how active things are at the moment but it would be great to have 1.2.1 released for cocoapods, much appreciated.
https://github.com/CocoaPods/Specs/tree/9543734012238c33ea018af5a4381459c13f0916/Specs/0/6/4/APNGKit

Thanks!

**Comment by onevcat** [comment]
1.2.2 was released with CocoaPods support.
