### ISSUE TITLE
Please use https-URL for `libpng-apng` git-submodule.

### ISSUE THREAD

**Issue by inamiy** [onevcat/APNGKit#11]
I just found `url = git@github.com:onevcat/libpng.git` in `.gitmodules` and prefer changing this to public https-URL so that it will work for unconfigured CI servers as well :wink:

**Comment by onevcat** [comment]
Oh, yes you are right.

**Comment by inamiy** [comment]
Thanks! 
Just saw bc43b22c51811cdefe34bfd9d5e87e3b9f7e2c9f, so I will close this issue.
