### ISSUE TITLE
Missing PLTE before IDAT

### ISSUE THREAD

**Issue by alexionut** [onevcat/APNGKit#115]
I have converted some gifs to apng files. But I am getting this error when I'm trying to use them:

imagePNG_error_break:445: *** ERROR: imagePNG_error_break
handle_error:269: IDAT: Missing PLTE before IDAT

What does it mean? How can I get these files to work?

**Comment by onevcat** [comment]
Try to upgrade to the latest version.

**Comment by alexionut** [comment]
Oh thank you, I didn't notice you released an update. I've been tackling this issue for a few days. It does work with the new version

**Comment by onevcat** [comment]
Thanks for the feedback! 😀
