### ISSUE TITLE
Is it possible to add log print property?

### ISSUE THREAD

**Issue by naijoug** [onevcat/APNGKit#128]
![image](https://user-images.githubusercontent.com/5566978/170226763-468aefc2-2680-4636-833f-15388e0410f0.png)

![image](https://user-images.githubusercontent.com/5566978/170226271-ee5ac9f0-2ea4-4495-9827-742e76d58d34.png)

If the APNG image missed frame, the log  will always print. It overwrite other debug log.

**Comment by onevcat** [comment]
Oh. That is quite surprising it keeps missing frames. Instead of only adding the debug log flag, can you also share me the APNG file causing the problem, then I can try to check and see how can I improve this. (And if it is possible also let me know the type of your test device. Thank you!)

**Comment by naijoug** [comment]
Thanks for your reply!

- File : [heart.zip](https://github.com/onevcat/APNGKit/files/8779802/heart.zip)
- Device : iPhoneX
- iOS Version : 15.4.1

**Comment by onevcat** [comment]
`LogLevel` was added in #129 and will be released soon as the next minor version. At the same time you can temporarily use the `master` branch to have this change for now.
