### ISSUE TITLE
animation time, no animation on iphone 

### ISSUE THREAD

**Issue by rickysou** [onevcat/APNGKit#13]
could i set the total animation time? the total duration time of the apng is 1.5s and when i play the animation on iphone ,  there is not any animation . when run in simulator , have animation but seems weird, what is the reason? the duration of the apng is too short?

**Comment by onevcat** [comment]
May I get the file you are using?

**Comment by rickysou** [comment]
sure, great thanks for giving a hand.


2016-03-03 10:57 GMT+08:00 Wei Wang <notifications@github.com>:

**Comment by rickysou** [comment]
change the filename extension to .apng but not .png, solved the problem
