### ISSUE TITLE
Question about creating APNG files feature

### ISSUE THREAD

**Issue by stzn** [onevcat/APNGKit#132]
(If it's not a proper place to ask questions, please tell me. )

Hi, I have a question about creating APNG files.

According to README, it is said that "The creating feature will be developed later." 

Do you have any plan to implement it? I'm looking for the feature to create APNG files from static images in Swift (Maybe [this is the one](https://github.com/ibireme/YYImage/blob/master/YYImage/YYImageCoder.m#L2525), but it's in Objective-C.)

Thank you.

**Comment by onevcat** [comment]
There is a plan for that, but since it is my hobby and free-time project, I did not yet now find some time for it yet. So sorry but there is no concrete time schedule for this.
