### ISSUE TITLE
Errors when building for Xcode 14.3

### ISSUE THREAD

**Issue by electricalen** [onevcat/APNGKit#133]
The minimum deployment target project settings don't work in 14.3.

**Comment by juanctecdam** [comment]
Same issue here. Any advice?

**Comment by onevcat** [comment]
I guess it was just the demo app, is that true?

The APNGKit framework itself builds without problem when I tested it with Xcode 14.3.

The demo version was fixed in #134 so I will close it now.

Feel free if you still has any problem when building the project.
