### ISSUE TITLE
Add a Privacy Manifest file

### ISSUE THREAD

**Issue by TrinhNTLine** [onevcat/APNGKit#143]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file.
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Is there any plans to add a privacy manifest?
Thanks!!!

**Comment by onevcat** [comment]
Although APNGKit is not using any of these APIs neither collecting any user information, I will add one soon. Stay tuned.

**Comment by onevcat** [comment]
Done and released in 2.3.0.
