### ISSUE TITLE
Add support xCode 8

### ISSUE THREAD

**Issue by mvyrko** [onevcat/APNGKit#17]
Now, I'm working in xCode 8 and your pod is unbuildable.

**Comment by RomeHein** [comment]
Yeah would be great to have it on swift 3!

**Comment by GDXRepo** [comment]
Yep, the same problem. Please update your framework to Swift 3, at least in the separated project. I really need your framework's functionality in my current project.

**Comment by lumenlunae** [comment]
Hello! I'd like to let the owner know I'm very thankful for this project--am really looking forward to seeing writing/saving functionality. 

I've started work on a swift 3 branch here: https://github.com/lumenlunae/APNGKit/tree/swift3 it builds and runs all the demos and passes all the tests. :) This is my first time working with C-interop though, so I don't know if this is properly way to handle everything. But for now just happy it works. :D

**Comment by GDXRepo** [comment]
Exciting news! I'll try it in my project today.

**Comment by onevcat** [comment]
@lumenlunae Wow, great work!

I created a [swift3 branch](https://github.com/onevcat/APNGKit/tree/swift3). If you'd like, you could send a pull request and I will check it and merge.

Thanks!

**Comment by GDXRepo** [comment]
Issue can be closed, working good with Xcode 8 GM Seed & Swift 3.
