### ISSUE TITLE
fatal error: The APNG meta should exists.

### ISSUE THREAD

**Issue by xiles** [onevcat/APNGKit#29]
App crashes with this fatal error message.
APNGImage() should return nil instead crashing an app.

**Comment by onevcat** [comment]
Fixed in 0.4.1.

**Comment by JGVB** [comment]
@onevcat I'm getting a crash when I create an APNGImage with data and scale.

It's crashing on this line:
https://github.com/onevcat/APNGKit/blob/252ae33500e8faabb67caeea4a93ea7e50ae98fc/APNGKit/Disassembler.swift#L460
