### ISSUE TITLE
blend over 貌似有些问题

### ISSUE THREAD

**Issue by ibireme** [onevcat/APNGKit#3]
![img_2215](https://cloud.githubusercontent.com/assets/839283/9781548/35661bb0-57c8-11e5-9c5d-ccec9e76a0fe.PNG)
如图，上面是APNGKit的实现，下面是ImageIO的实现。

**Comment by onevcat** [comment]
是指边缘锯齿和颜色有点偏差么？

**Comment by ibireme** [comment]
对，边缘貌似是没处理好，和 Firefox、ImageIO 的渲染不太一样。

**Comment by onevcat** [comment]
可能是计算那边精度处理的问题，我有空的话会去看看。感谢提出。

**Comment by onevcat** [comment]
APNGKit v2 was released and this is fixed!
