### ISSUE TITLE
Animation stops when scrolling

### ISSUE THREAD

**Issue by JGVB** [onevcat/APNGKit#31]
I have an APNGImageView in a collection view and whenever I start scrolling, the animation pauses.  Once I stop scrolling, the animations speeds up and appears to catch up to where it would have been.  How do I make it so the animation doesn't stop when scrolling?

**Comment by JGVB** [comment]
AllowAnimationInscroll Found it. Wish I could delete issues!

**Comment by revolter** [comment]
@JGVB, What is `AllowAnimationInscroll`?
