### ISSUE TITLE
Crash when I create an APNGImage with data and scale (On Clean)

### ISSUE THREAD

**Issue by JGVB** [onevcat/APNGKit#32]
It's crashing on this line:
https://github.com/onevcat/APNGKit/blob/252ae33500e8faabb67caeea4a93ea7e50ae98fc/APNGKit/Disassembler.swift#L460

It's a valid png image

"bad adaptive filter value" is logged out
Other times "libpng error: IDAT: CRC error" is logged out

Context: Many APNGImageViews are being used in collection view cells (reused)

**Comment by onevcat** [comment]
Does this happen 100% for a specified PNG file, or is it random?

**Comment by JGVB** [comment]
@onevcat   It's random on different PNG files.  I have a feeling it could have to do with cell reuse, but I could be wrong.

**Comment by onevcat** [comment]
APNGKit v2 was release and it now does not depend on libpng. So this should not happen anymore.
