### ISSUE TITLE
setjmp is no longer available in Swift 3.1 and isn't coming back

### ISSUE THREAD

**Issue by samsonjs** [onevcat/APNGKit#34]
Disassembler.swift uses setjmp which doesn't compile anymore. I don't understand this code well enough to propose a solution but with some direction I can give it a shot.

https://github.com/mattgallagher/CwlPreconditionTesting/issues/7

**Comment by onevcat** [comment]
Thanks for letting me know that.

0.4.4 was released for it.

**Comment by samsonjs** [comment]
Excellent. Thank you!
