### ISSUE TITLE
Project Bitcode issue

### ISSUE THREAD

**Issue by marcuswu0814** [onevcat/APNGKit#37]
In out project, we setting the `OTHER_CFLAGS` to `-fembed-bitcode` but it show error:

~~~
Showing All Errors Only
ld: bitcode bundle could not be generated because '.../Build/Products/Debug-iphoneos/APNGKit/APNGKit.framework/APNGKit' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
~~~

Is any setting missing or APNGKit didn't support bitcode?

**Comment by onevcat** [comment]
@marcuswu0814 

APNGKit supports bitcode. If you are using Carthage to build the framework, it might be related to this issue. https://github.com/Carthage/Carthage/issues/535

I'll try to add it now and please let me know the result.

**Comment by onevcat** [comment]
@marcuswu0814 

Oh, after some further investigating, it seems that Carthage has resolved it already: https://github.com/Carthage/Carthage/pull/839

Maybe you are using a very old version of Carthage? Could you try to upgrade your Carthage and try again?

**Comment by marcuswu0814** [comment]
Sorry, I using cocoapod to install APNGKit, so if I try to using Carthage, maybe I can fix this issue?

**Comment by onevcat** [comment]
Maybe, I am not sure about it since there is no such report before. But it's worth to try.

**Comment by marcuswu0814** [comment]
@onevcat Thanks you very much and I will try to using Carthage to build framework later. 👍

**Comment by marcuswu0814** [comment]
I try to using Carthage to add framework to our project. (In workplace's another framework project)

But face this issue:

~~~

dyld: Library not loaded: @rpath/APNGKit.framework/APNGKit
  Referenced from: /private/var/containers/Bundle/Application/.../Frameworks/our.framework/our
  Reason: no suitable image found.  Did find:

/private/var/containers/Bundle/Application/F41A8098-E806-4847-AA08-3E37F0218788/.../Frameworks/our.framework/Frameworks/APNGKit.framework/APNGKit: required code signature missing for '/private/var/containers/Bundle/Application/.../my.app/Frameworks/our.framework/Frameworks/APNGKit.framework/APNGKit'

~~~

Could you give me some tips? I try lots of ways to solve this issue. :(
Like copy framework, adding Runpath Search Paths... etc.

**Comment by onevcat** [comment]
It means you are not copying the framework to app bundle. You need to follow the Carthage instruction to add a framework copy phase (with carthage's copy framework command line) to use it.

**Comment by marcuswu0814** [comment]
I think I already did that, like following setting:

1. In project `build phases` tab
2. Adding a `run script phases`
3. Adding `/usr/local/bin/carthage copy-frameworks` 
4. Input files `$(SRCROOT)/Carthage/Build/iOS/APNGKit.framework`

and

1. In project `build phases` tab
2. Adding a `copy files phases`
3. Destination set value to `Frameworks`
4. Name adding a `APNGKit.framework` and Code sign on copy is `on`

I'm sure a follow the step to set all of these setting but it still not work and I don't know how to check if above setting is setting successful.

**Comment by onevcat** [comment]
Just had another read of your error message. It seems that you are trying to use APNGKit in your own framework target, instead of an application target?

I believe it is not the correct way to "embed" a dynamic framework into another framework. The depended framework should also be loaded dynamically, by the final application target.

**Comment by marcuswu0814** [comment]
Finally, my team leader try to add `APNGKit` into another share framework target (in our Workplace’s another project) by `CocoaPod`, which didn’t be used by `Share extension target`.

I didn’t know why and can’t ensure is that the key point cause this issue. But I think if I add it into above frameworks by `Carthage`, it may also work.

If you need much more information about this issue, I can try to provide it. 

Anyway, it working very well now. 👍  
I'm really thanks for your help and so sorry spend lots of your time. 😭

**Comment by onevcat** [comment]
@marcuswu0814 Thank you for your feedback. Glad to hear that. 

Since there is no other report on this, I think I would just close it now. If anyone else encountered the similar issue, just reopen it and I will dig into it deeper.
