### ISSUE TITLE
Do you know any android lib that supports playing APNG well?

### ISSUE THREAD

**Issue by ltebean** [onevcat/APNGKit#43]
Hi, we are using your APNGKit in our iOS project, and it works very well. But for Android,
we just tried some libs listed here: https://github.com/search?l=Java&q=apng&type=Repositories&utf8=%E2%9C%93, and none of them does the job well. Can you recommend us some good android libs to play APNG, thanks!

**Comment by onevcat** [comment]
Hey,

I am not an Android developer at all and I cannot give you any suggestion on it. Sorry!
