### ISSUE TITLE
How to use `addArrangedSubview` while working with uistackview

### ISSUE THREAD

**Issue by knishant90** [onevcat/APNGKit#44]
When using the `addArrangedSubview` to uistackview it sets the width and height by default to 0. Is there a way I can call this function instead of doing `addSubview` ?

**Comment by onevcat** [comment]
As indicated in #46, an `intrinsicContentSize` was added so this should be already solved.

And in the latest released APNGKit v2, it is considered from the very beginning to the layout should not break anymore.

I am closing it. If anyone finds a similar problem, please feel free to open a new one.
