### ISSUE TITLE
Crash when load a normal png

### ISSUE THREAD

**Issue by pablogeek** [onevcat/APNGKit#47]
I'm trying to load a normal png and it crashes ```libpng error: CgBI: unhandled critical chunk```

Is there any way to check if the image is an APNG or normal PNG?

**Comment by onevcat** [comment]
APNGKit should work properly for a normal PNG. It could happen if the PNG file itself not respect PNG specification.

May I get the image which causes this problem so I could have a look?

**Comment by sepehrrezaei** [comment]
i have this problem 
this is the png file : 
![2](https://user-images.githubusercontent.com/54465154/63633150-932afb00-c658-11e9-8e25-7888dc6dae1b.png)
and the screen shot of error : 
<img width="912" alt="Screen Shot 2019-08-24 at 10 19 38 AM" src="https://user-images.githubusercontent.com/54465154/63633160-b81f6e00-c658-11e9-8dd7-2cdeaf864499.png">

**Comment by onevcat** [comment]
APNGKit v2 was released. Now loading a normal PNG will not cause a jmp but throwing a Swift error. You can then catch the error and fallback to a static version of image. Please read the guide in README file to know more.

I am closing this.
