### ISSUE TITLE
Carthage in Objective-C context

### ISSUE THREAD

**Issue by dionysiusmarquis** [onevcat/APNGKit#57]
Hey,

I'm trying to use APNGKit with Carthage in Objective-C context. I can't use Swift because its an Unity project. Is this combination possible? I imported `<APNGKit/APNGKit-Swift.h>` but the header file does only expose the default `init` and `initWithDecoder` methods. I tried `[[APNGImage alloc] contentsOfFile:@""]` wich throws `No visible @interface for 'APNGImage' declares the selector 'contentsOfFile:'`

**Comment by onevcat** [comment]
I am not sure but maybe it is related to the default value of `@objc` infer in Swift 4. In the latest Swift 4, this inference is off by default, it might cause the functions and properties not available in Objective-C. Maybe try to turn the "Swift 3 @objc inference" to on in the build setting of APNGKit might solve your problem.

See [this post](https://useyourloaf.com/blog/objc-warnings-upgrading-to-swift-4/) for more on `@objc` inference. Basically, you need do reverse in the "Completing The Migration" section.

**Comment by dionysiusmarquis** [comment]
Yes, that would actually work for now. One thing is that `carthage update` will check out APNGKit `*** Checking out APNGKit at "1.0.0"` and reset the settings before build. The other thing is that Xcode will throw Swift 4 deprecation warnings:
```
Swift initializer 'APNGImage.init(named:progressive:in:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint
```

```
Swift initializer 'APNGImageView.init(image:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C 
```

Sounds like this workaround won't be available forever.

**Comment by Desgard** [comment]
@dionysiusmarquis I also get this problems. And I write a view to carry the `APNGImageView` in Swift. And its interface can support ObjC. 😄

**Comment by zgpeace** [comment]
你好，我的工程是objc，按照你说的 Maybe try to turn the "Swift 3 @objc inference" to on in the build setting of APNGKit might solve your problem.， 还是找不到方法 contentsOfFile: 。  
我是通过Carthage生成的framework，
头文件引用：
 #import "MyProject-Swift.h"
#import <APNGKit/APNGKit-Swift.h>

Product Module Name: Should be your app target's name
Defines Module: YES
Embedded Content Contains Swift: YES (deprecated)  
请用 ALWAYS EMBED SWIFT STANDARD LIBRARIES
参考： https://stackoverflow.com/questions/38792650/embedded-content-contains-swift-code-with-xcode-8-beta

Install Objective-C Compatibility Header: YES

**Comment by onevcat** [comment]
Carthage and Objective-C is dropped in APNGKit v2. Now it is a pure Swift project and recommended managed by SPM.

I am closing this for now.
