### ISSUE TITLE
libpng error in console: libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by TenderChang** [onevcat/APNGKit#58]
I have met an issue that an error shows in console:
libpng warning: iCCP: known incorrect sRGB profile
and it will increase the memory & CPU's usage, and then crash :(
can you help me with this?

**Comment by onevcat** [comment]
Hi, @TenderChang 

Thanks for reporting this. Could you upload or give a link to the image which causing this issue?

**Comment by TenderChang** [comment]
Hi, @onevcat 
Thanks for your responding.
I found out that my app will compress those images, that's why the error shows in console.
And I used @autoreleasepool to solve the memory issue.
