### ISSUE TITLE
Unexpected output result for specific apng files

### ISSUE THREAD

**Issue by jaumevn** [onevcat/APNGKit#65]
Hello, I've been using the library for quite a long time, and it's great. Recently I found an issue with specific apng files which leads to and unexpected output when loading the file with the library. There is no different method when loading apng files, it just happen sometimes to specific files.

Here you have a video of the glitch (look at the vertical line created between the letter t and y):
![actual-result](https://user-images.githubusercontent.com/884454/37398687-959095f4-277f-11e8-937a-beb7b5e655c5.gif)

And here the expected result:
![expected-result](https://user-images.githubusercontent.com/884454/37398592-51031344-277f-11e8-8d8e-5fea32bf251e.gif)

Here you can download all the related files:
[apng-bugreport.zip](https://github.com/onevcat/APNGKit/files/1810716/apng-bugreport.zip)

Thanks

**Comment by onevcat** [comment]
The file in this zip turns to be a GIF instead of APNG.

**Comment by jaumevn** [comment]
@onevcat the apng file is inside the zip file. It is named as `source.apng`.
<img width="882" alt="screenshot 2018-03-26 09 09 01" src="https://user-images.githubusercontent.com/884454/37891661-5fe07d34-30d5-11e8-9793-ba0fb6502c7f.png">

**Comment by onevcat** [comment]
APNGKit v2 was just release and it contains a much better, robust implementation and it is passing all APNG spec tests now. This should not happen in the new version anymore.
