### ISSUE TITLE
Animation faster after send app background

### ISSUE THREAD

**Issue by carlosDigio** [onevcat/APNGKit#73]
I tested this lib and while showing an apng and send app to background, when come back again the animation goes faster.

Video:
https://youtu.be/tYIKYy4dQ7A

**Comment by Leo7654** [comment]
Please check this https://github.com/onevcat/APNGKit/pull/62 .

**Comment by w4-hojin** [comment]
Please check this https://github.com/onevcat/APNGKit/pull/62

**Comment by carlosDigio** [comment]
Pull request #74
