### ISSUE TITLE
Podspec

### ISSUE THREAD

**Issue by brightsider** [onevcat/APNGKit#80]
Update podspec for Swift 4.2

**Comment by amedakedo** [comment]
Was wondering if there is a specific reason as to why podspec is not updated for Swift 4.2 yet?

As a workaround I'm currently using the Swift 4.2 update by setting the specific commit in my Podfile
like so
```
pod 'APNGKit', :git => 'https://github.com/onevcat/APNGKit.git', :commit => 'fdc3f971e1887c7bd547bb68c49fe845e8bfa1a3'
```

but instead I would like to be able able to just set it normally like
```
pod 'APNGKit', '~> 1.0.4'
```

Thanks in advance 🙏

**Comment by onevcat** [comment]
Too busy recently. I would take a look it tonight maybe.

**Comment by onevcat** [comment]
Tag 1.1.0 was created, with podspec updated for Swift 4.2.

Sorry for the delay!
