### ISSUE TITLE
Crash when Objective-C dealloc

### ISSUE THREAD

**Issue by sidepelican** [onevcat/APNGKit#83]
Sometimes my app crashes when removing `APNGImageView` in Objective-C coded `UIViewController` .
In case of Swift, that's not happen.

I think this workaround is not enough for Objective-C.
https://github.com/onevcat/APNGKit/blob/ccad7588e3428bfcd53862f457c5bda61f298e9f/APNGKit/APNGImageView.swift#L168-L169
In Objective-C, sometimes `deinit` is not called when removing the `APNGImageView` from the parent view  because of `AutoreleasePool`. So this workaround dose not affect, and crash it.

**Comment by onevcat** [comment]
APNGKit v2 was just released and should fix this. (However, I am not sure if that version still supports Objective-C, I guess not). After all, APNGKit is now only targeting Swift use.
