### ISSUE TITLE
How do I use this with iMessage Stickers?

### ISSUE THREAD

**Issue by TyrantBoy** [onevcat/APNGKit#87]
MSStickers object expects an URL. How do I use this with the iMessage Stickers?

**Comment by onevcat** [comment]
I am not an expert of iMessage Sticker. Maybe you just need to download the image data from the URL first and create an `APNGImage` with these data? See #94

**Comment by TyrantBoy** [comment]
you just need open the app inside of iMessage. Hold down a stickmoji
character and drag it over a message bubble, then release it to stick.
