### ISSUE TITLE
no functions visible in objective C

### ISSUE THREAD

**Issue by halpz** [onevcat/APNGKit#89]
I can't see any init functions for either APNGImage or APNGImageView when trying to use in objective-c 

I can see the Class name, but can't access any properties or functions
(using swift 4.2 in OBjective C project)

**Comment by onevcat** [comment]
From Swift 4, the `@objc` is now not implicitly added to `NSObject`, so the related things will not be exposed to Objective-C now.

This framework does not design for or tested with Objective-C context.

**Comment by halpz** [comment]
so it no longer supports objective-c?

should maybe update the readme then

**Comment by onevcat** [comment]
I have no time for adding Objective-C support back right now since I only use it in my Swift projects. But any contributing on this topic is welcomed.
