### ISSUE TITLE
Can I load APNG image from URL ?

### ISSUE THREAD

**Issue by TungVuDuc2805** [onevcat/APNGKit#94]

**Comment by uhooi** [comment]
@TungVuDuc2805 
You can load APNG Image from `URL` by adding an initializer to `APNGImage` with Extension.

```swift
import APNGKit

extension APNGImage {
    convenience init?(urlString: String?) {
        guard let urlString = urlString, let url = URL(string: urlString) else {
            return nil
        }
        self.init(url: url)
    }
    
    convenience init?(url: URL) {
        guard let data = try? Data(contentsOf: url) else {
            return nil
        }
        self.init(data: data)
    }
}
```

Usage:

```swift
apngImageView.image = APNGImage(urlString: "https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png")
apngImageView.startAnimating()
```

ref: https://github.com/uhooi/APNGSample/blob/master/APNGSample/APNGImage%2BURL.swift

**Comment by onevcat** [comment]
As indicated by @uhooi this is done for now. There is a plan to also support built-in downloading and cache with the help of [another library Kingfisher](https://github.com/onevcat/Kingfisher) as a plugin. But that is another story. I am closing this for now.
