### ISSUE TITLE
Swift 5 upgrade

### ISSUE THREAD

**Issue by eitanaviv** [onevcat/APNGKit#95]
Using Xcode 11 GM with Swift 5 tells me to convert APNGKit to support Swift 5.
I can see only one line of code needs to be changed, will we see an update for that?
Thanks!

![image](https://user-images.githubusercontent.com/35567702/64757919-1d6dcd00-d53c-11e9-94bc-17984a265d6f.png)

**Comment by onevcat** [comment]
Hey,

Maybe soon!

**Comment by michaelamici** [comment]
do it now you lazy bum

**Comment by onevcat** [comment]
APNGKit supports Swift 5 from v1.2 and now APNGKit v2 was also released with full support for the latest tech. I am closing this.
