### ISSUE TITLE
The first frame is skipped (even when it's not set to skip) when calling startAnimating

### ISSUE THREAD

**Issue by imbrig** [onevcat/APNGKit#96]
The first frame is skipped (even when it's not set to skip) when calling startAnimating and when calling stopAnimating and then startAnimating again, the frame when stop was called is shown briefly.
Attached is a test image with frames red[1], yellow[2], green[3], blue[4].
![test_sequence](https://user-images.githubusercontent.com/47464835/74901354-78131c80-5357-11ea-816a-e7dc72514ea4.png)

I resolved this by changing startAnimating function by adding

        guard let image = image else {
            return
        }
        let frameIndex: Int = image.firstFrameHidden ? 1 : 0
        currentFrameIndex = frameIndex
        let frame = image.next(currentIndex: currentFrameIndex)
        currentFrameDuration = frame.duration
        updateContents(frame.image)

see https://github.com/imbrig/APNGKit/commit/0b003f19e77a9e51881dbc83ebfdb62fb3a478fb

**Comment by onevcat** [comment]
@imbrig Thanks for reporting this! I think you are correct and the fix works. I will check if there is a better way to do it. If no, I will send a PR with your fix and release an update soon!

Thank you!

**Comment by onevcat** [comment]
The `firstFrameHidden` should be handled inside the `image.next(currentIndex)` and internal disassembler. So we do not need to calculate the frame index here.

**Comment by imbrig** [comment]
@onevcat That's great! Looking forward to the next release!
