### ISSUE TITLE
An unexpected version directory `libpng-apng`

### ISSUE THREAD

**Issue by BlankConan** [onevcat/APNGKit#99]
mac version : 10.14.5
xcode version : 11.3(11C29)
pod version : 1.8.4

mac的工程，开发语言objective-c

 pod install error：

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-TYTYTY`:
  (``)

Finding Podfile changes
  A APNGKit

Resolving dependencies of `Podfile`
[!] An unexpected version directory `libpng-apng` was encountered for the `~/.cocoapods/repos/onevcat/APNGKit` Pod in the `APNGKit` repository.

**Comment by onevcat** [comment]
APNGKit v2 was just released without depending on libpng anymore. So it won't happen. I am closing this.
